name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: build
        build_script: npm install && npm run build